In [2]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('Self_admitted_technical_debt_identified_and_removed_for_the_Log4j_project.csv', encoding='ISO-8859-1')
dev = df[df['has_removed_version'] == 'f']
d =dev['comment_text'].values.tolist()
d

['//Use a StringBuffer in lieu of String concatenation -- it is //much more efficient this way.',
 '// writing directly the Class object would be nicer, except that // serialized a Class object can not be read back by JDK // 1.1.x. We have to resort to this hack instead.',
 '// Note that we use Class.getDeclaredMethod instead of // Class.getMethod. This assumes that the Level subclass // implements the toLevel(int) method which is a // requirement. Actually, it does not make sense for Level // subclasses NOT to implement this method. Also note that // only Level can be subclassed and not Priority.',
 '// We could not find resource. Ler us now try with the // classloader that loaded this class.',
 '// convert to specified encoding - which may be sequence of // 8-bit chars, or multi-byte encodings like UTF-8 or UTF-16. // The receiving end had better be expecting whatever encoding // is used here on the sending end!',
 '/* this Appender is not supposed to be used for logging of Exception

In [29]:
dev = df['removed_version_author'].unique()
len(dev)

8

In [33]:
import pandas as pd
from scipy.stats import chi2_contingency

# Create a DataFrame with the provided data
data = {
    'Number of commits': [2000, 5000, 3000, 800, 400],
    'Number of technical debt commits': [1164, 4331, 1317, 136, 271],
    'Number of commits SATD removed': [472, 3926, 1009, 118, 208],
    'Remaining percentage of commits': [692, 405, 308, 18, 64],
    'Total developer': [113, 1368, 160, 230, 585],
    'Days active': [4228, 6083, 6440, 4932, 8351],
    'Number of releases': [35, 98, 11, 54, 7],
    'Number of Community smell before SATD removal': [7, 8, 5, 7, 8],
    'Number of Community smell after SATD removal': [2, 2, 3, 2, 2],
    'Number of SATD introduced developers': [64, 47, 19, 8, 28],
    'Number of SATD removal developers': [38, 37, 15, 7, 16]
}

df = pd.DataFrame(data)

# Extract the relevant columns for the chi-square test
observed_data = df[[
                    'Number of technical debt commits',
                    'Number of SATD introduced developers',
                    'Number of SATD removal developers', 
                    # 'Number of commits SATD removed',
                    'Number of Community smell before SATD removal', 
                    # 'Number of Community smell after SATD removal'
            ]]

# Perform the chi-square test
chi2_stat, p_value, dof, expected = chi2_contingency(observed_data)

# Print the results
print(f"Chi-Square Statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


Chi-Square Statistic: 312.05207771232824
P-value: 1.3791382198127103e-59
Degrees of Freedom: 12
Expected Frequencies:
[[1.21993721e+03 2.80523032e+01 1.90958449e+01 5.91464224e+00]
 [4.23863494e+03 9.74668791e+01 6.63479357e+01 2.05502456e+01]
 [1.29947750e+03 2.98813222e+01 2.03409000e+01 6.30027877e+00]
 [1.51414045e+02 3.48174698e+00 2.37010487e+00 7.34103279e-01]
 [3.09536307e+02 7.11774857e+00 4.84521439e+00 1.50073012e+00]]


In [49]:
import random

# Number to divide
num_to_divide = 50

# Divide by 6
result = num_to_divide / 4

# Generate random percentages
random_percentages = [random.uniform(0, 100) for _ in range(6)]

# Calculate values with random percentages
results_with_random_percentages = [result * (percentage / 100) for percentage in random_percentages]

# Display the results
print(f"Original Result: {result}")
print("Results with Random Percentages:")
for i, value in enumerate(results_with_random_percentages, start=1):
    print(f"Scenario {i}: {value:.2f}")


TypeError: 'int' object is not callable